name: build-driver

on:
  push:
    paths: ["bypassdrv.c", "bypassdrv.h"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: compile driver
        shell: cmd
        run: |
          for /d %%i in ("C:\Program Files (x86)\Windows Kits\10\Lib\*") do set WDK=%%~ni
          echo SDK version: %WDK%
          cl /nologo /O2 /W3 /kernel /D_AMD64_ /Fe:RatBE.sys bypassdrv.c ^
            /link /DRIVER /ENTRY:DriverEntry ^
            "C:\Program Files (x86)\Windows Kits\10\Lib\%WDK%\km\amd64\ntoskrnl.lib" ^
            "C:\Program Files (x86)\Windows Kits\10\Lib\%WDK%\km\amd64\hal.lib" ^
            "C:\Program Files (x86)\Windows Kits\10\Lib\%WDK%\km\amd64\wdmsec.lib"
      - uses: actions/upload-artifact@v4
        with:
          name: driver
          path: RatBE.sys
